# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(700, 300)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(700, 300))
        #MainWindow.setMaximumSize(QtCore.QSize(700, 300))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_10 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.mainLayout = QtWidgets.QVBoxLayout()
        self.mainLayout.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.mainLayout.setObjectName("mainLayout")
        self.sourceLayout = QtWidgets.QHBoxLayout()
        self.sourceLayout.setObjectName("sourceLayout")
        self.urlLabel = QtWidgets.QLabel(self.centralwidget)
        self.urlLabel.setObjectName("urlLabel")
        self.sourceLayout.addWidget(self.urlLabel)
        self.urlInput = QtWidgets.QLineEdit(self.centralwidget)
        self.urlInput.setText("")
        self.urlInput.setObjectName("urlInput")
        self.sourceLayout.addWidget(self.urlInput)
        self.mainLayout.addLayout(self.sourceLayout)
        self.coordLayout = QtWidgets.QHBoxLayout()
        self.coordLayout.setObjectName("coordLayout")
        self.rowLayout = QtWidgets.QVBoxLayout()
        self.rowLayout.setObjectName("rowLayout")
        self.rowLabel = QtWidgets.QLabel(self.centralwidget)
        self.rowLabel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.rowLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.rowLabel.setObjectName("rowLabel")
        self.rowLayout.addWidget(self.rowLabel)
        self.rowCoordLayout = QtWidgets.QHBoxLayout()
        self.rowCoordLayout.setObjectName("rowCoordLayout")
        self.xMinInput = QtWidgets.QSpinBox(self.centralwidget)
        self.xMinInput.setMinimumSize(QtCore.QSize(98, 0))
        self.xMinInput.setMaximumSize(QtCore.QSize(98, 16777215))
        self.xMinInput.setMaximum(999999999)
        self.xMinInput.setObjectName("xMinInput")
        self.rowCoordLayout.addWidget(self.xMinInput)
        self.rowDecoration = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rowDecoration.sizePolicy().hasHeightForWidth())
        self.rowDecoration.setSizePolicy(sizePolicy)
        self.rowDecoration.setMaximumSize(QtCore.QSize(10, 16777215))
        self.rowDecoration.setAlignment(QtCore.Qt.AlignCenter)
        self.rowDecoration.setObjectName("rowDecoration")
        self.rowCoordLayout.addWidget(self.rowDecoration)
        self.xMaxInput = QtWidgets.QSpinBox(self.centralwidget)
        self.xMaxInput.setMinimumSize(QtCore.QSize(98, 0))
        self.xMaxInput.setMaximumSize(QtCore.QSize(98, 16777215))
        self.xMaxInput.setMinimum(1)
        self.xMaxInput.setMaximum(999999999)
        self.xMaxInput.setProperty("value", 1)
        self.xMaxInput.setObjectName("xMaxInput")
        self.rowCoordLayout.addWidget(self.xMaxInput)
        self.rowLayout.addLayout(self.rowCoordLayout)
        self.coordLayout.addLayout(self.rowLayout)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.coordLayout.addItem(spacerItem)
        self.colLayout = QtWidgets.QVBoxLayout()
        self.colLayout.setObjectName("colLayout")
        self.colLabel = QtWidgets.QLabel(self.centralwidget)
        self.colLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.colLabel.setObjectName("colLabel")
        self.colLayout.addWidget(self.colLabel)
        self.colCoordLayout = QtWidgets.QHBoxLayout()
        self.colCoordLayout.setObjectName("colCoordLayout")
        self.yMinInput = QtWidgets.QSpinBox(self.centralwidget)
        self.yMinInput.setMinimumSize(QtCore.QSize(98, 0))
        self.yMinInput.setMaximumSize(QtCore.QSize(98, 16777215))
        self.yMinInput.setMaximum(999999999)
        self.yMinInput.setObjectName("yMinInput")
        self.colCoordLayout.addWidget(self.yMinInput)
        self.colDecoration = QtWidgets.QLabel(self.centralwidget)
        self.colDecoration.setMaximumSize(QtCore.QSize(10, 16777215))
        self.colDecoration.setAlignment(QtCore.Qt.AlignCenter)
        self.colDecoration.setObjectName("colDecoration")
        self.colCoordLayout.addWidget(self.colDecoration)
        self.yMaxInput = QtWidgets.QSpinBox(self.centralwidget)
        self.yMaxInput.setMinimumSize(QtCore.QSize(98, 0))
        self.yMaxInput.setMaximumSize(QtCore.QSize(98, 16777215))
        self.yMaxInput.setMinimum(1)
        self.yMaxInput.setMaximum(999999999)
        self.yMaxInput.setProperty("value", 1)
        self.yMaxInput.setObjectName("yMaxInput")
        self.colCoordLayout.addWidget(self.yMaxInput)
        self.colLayout.addLayout(self.colCoordLayout)
        self.coordLayout.addLayout(self.colLayout)
        self.mainLayout.addLayout(self.coordLayout)
        spacerItem1 = QtWidgets.QSpacerItem(20, 50, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.mainLayout.addItem(spacerItem1)
        self.buttonLayout = QtWidgets.QHBoxLayout()
        self.buttonLayout.setObjectName("buttonLayout")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.buttonLayout.addItem(spacerItem2)
        self.startButton = QtWidgets.QPushButton(self.centralwidget)
        self.startButton.setMinimumSize(QtCore.QSize(250, 50))
        self.startButton.setMaximumSize(QtCore.QSize(250, 50))
        font = QtGui.QFont()
        font.setPointSize(19)
        font.setBold(True)
        font.setWeight(75)
        self.startButton.setFont(font)
        self.startButton.setObjectName("startButton")
        self.buttonLayout.addWidget(self.startButton)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.buttonLayout.addItem(spacerItem3)
        self.mainLayout.addLayout(self.buttonLayout)
        self.statusLayout = QtWidgets.QVBoxLayout()
        self.statusLayout.setObjectName("statusLayout")
        self.statusBar = QtWidgets.QProgressBar(self.centralwidget)
        self.statusBar.setProperty("value", 0)
        self.statusBar.setObjectName("statusBar")
        self.statusLayout.addWidget(self.statusBar)
        self.statusMessage = QtWidgets.QLabel(self.centralwidget)
        self.statusMessage.setAlignment(QtCore.Qt.AlignCenter)
        self.statusMessage.setObjectName("statusMessage")
        self.statusLayout.addWidget(self.statusMessage)
        self.mainLayout.addLayout(self.statusLayout)
        self.verticalLayout_10.addLayout(self.mainLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 700, 27))
        self.menubar.setObjectName("menubar")
        self.menuParam = QtWidgets.QMenu(self.menubar)
        self.menuParam.setObjectName("menuParam")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionPref = QtWidgets.QAction(MainWindow)
        self.actionPref.setObjectName("actionPref")
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.actionLang = QtWidgets.QAction(MainWindow)
        self.actionLang.setEnabled(False)
        self.actionLang.setObjectName("actionLang")
        self.actionHelp = QtWidgets.QAction(MainWindow)
        self.actionHelp.setObjectName("actionHelp")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.menuParam.addAction(self.actionPref)
        self.menuParam.addAction(self.actionLang)
        self.menuParam.addAction(self.actionQuit)
        self.menuHelp.addAction(self.actionHelp)
        self.menubar.addAction(self.menuParam.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.actionQuit.triggered.connect(MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "TilledMapDownloader"))
        self.urlLabel.setText(_translate("MainWindow", "URL"))
        self.urlInput.setPlaceholderText(_translate("MainWindow", "https://exemple.org/___x___/___y___.jpg"))
        self.rowLabel.setText(_translate("MainWindow", "ligne"))
        self.rowDecoration.setText(_translate("MainWindow", "⇒"))
        self.colLabel.setText(_translate("MainWindow", "colonne"))
        self.colDecoration.setText(_translate("MainWindow", "⇒"))
        self.startButton.setText(_translate("MainWindow", "Démarer"))
        self.statusMessage.setText(_translate("MainWindow", "En attente"))
        self.menuParam.setTitle(_translate("MainWindow", "Paramètres"))
        self.menuHelp.setTitle(_translate("MainWindow", "Aide"))
        self.actionPref.setText(_translate("MainWindow", "Préférences"))
        self.actionQuit.setText(_translate("MainWindow", "Quiter"))
        self.actionLang.setText(_translate("MainWindow", "Langue"))
        self.actionHelp.setText(_translate("MainWindow", "Aide en ligne"))
        self.actionAbout.setText(_translate("MainWindow", "À propos"))

